class IRValidator:

    def validate(self, ir):

        errors = []
        warnings = []

        # ==================================================
        # MAPPING
        # ==================================================

        if not ir.get("name"):
            errors.append(
                "Mapping name is missing"
            )

        # ==================================================
        # SOURCES
        # ==================================================

        sources = ir.get(
            "sources",
            []
        )

        if not sources:
            errors.append(
                "No sources found in IR"
            )

        source_names = set()

        for source in sources:

            source_name = source.get(
                "name"
            )

            if not source_name:
                errors.append(
                    "Source name is missing"
                )
                continue

            if source_name in source_names:
                errors.append(
                    f"Duplicate source found: "
                    f"{source_name}"
                )

            source_names.add(
                source_name
            )

            if not source.get(
                "connection"
            ):
                errors.append(
                    f"Source '{source_name}' "
                    f"has no resolved connection"
                )

            # ----------------------------------------------
            # Source columns
            # ----------------------------------------------

            columns = source.get(
                "columns",
                []
            )

            column_names = set()

            for column in columns:

                column_name = column.get(
                    "name"
                )

                if not column_name:
                    errors.append(
                        f"Source '{source_name}' "
                        f"has column with no name"
                    )
                    continue

                if column_name in column_names:
                    errors.append(
                        f"Duplicate column "
                        f"'{column_name}' found "
                        f"in source "
                        f"'{source_name}'"
                    )

                column_names.add(
                    column_name
                )

        # ==================================================
        # TARGETS
        # ==================================================

        targets = ir.get(
            "target",
            []
        )

        # IRGenerator currently represents a single target as a
        # dictionary, while older IR shapes may represent targets
        # as a list. Normalize both shapes here so validation is
        # independent of that representation detail.
        if isinstance(targets, dict):
            targets = [targets]
        elif targets is None:
            targets = []

        if not targets:
            errors.append(
                "No targets found in IR"
            )

        target_names = set()
        target_instance_names = set()

        # Store ports for transformations
        # and target instances.

        node_ports = {}

        for target in targets:

            target_name = target.get(
                "name"
            )

            if not target_name:

                errors.append(
                    "Target name is missing"
                )

                continue

            # ----------------------------------------------
            # Duplicate target definition
            # ----------------------------------------------

            if target_name in target_names:

                errors.append(
                    f"Duplicate target found: "
                    f"{target_name}"
                )

            target_names.add(
                target_name
            )

            # ----------------------------------------------
            # Target connection
            # ----------------------------------------------

            # A target generated by the current IRGenerator may
            # intentionally carry only the canonical target name
            # and instance name. Do not reject the IR merely because
            # the connection was not copied into this compact target
            # representation. If connection metadata is present,
            # validate that it is not empty.

            target_connection = target.get(
                "connection"
            )

            if target_connection is not None and not target_connection:
                errors.append(
                    f"Target '{target_name}' "
                    f"has an empty resolved connection"
                )

            # ----------------------------------------------
            # Target instance
            # ----------------------------------------------

            target_instance_name = target.get(
                "instance_name"
            ) or target.get(
                "name"
            )

            if not target_instance_name:

                errors.append(
                    f"Target '{target_name}' "
                    f"has no target instance name"
                )

            else:

                if target_instance_name in (
                    target_instance_names
                ):

                    errors.append(
                        f"Duplicate target instance "
                        f"found: "
                        f"{target_instance_name}"
                    )

                target_instance_names.add(
                    target_instance_name
                )

            # ----------------------------------------------
            # Target columns
            # ----------------------------------------------

            target_columns = target.get(
                "columns",
                []
            )

            # Current IRGenerator may store target ports under
            # target["ports"] instead of target["columns"].
            # Convert those ports into the same normalized column
            # shape used by the validator.
            if not target_columns:
                target_columns = target.get(
                    "ports",
                    []
                )

            target_column_names = set()

            for column in target_columns:

                column_name = column.get(
                    "name"
                )

                if not column_name:

                    errors.append(
                        f"Target '{target_name}' "
                        f"has column with no name"
                    )

                    continue

                if column_name in (
                    target_column_names
                ):

                    errors.append(
                        f"Duplicate column "
                        f"'{column_name}' found "
                        f"in target "
                        f"'{target_name}'"
                    )

                target_column_names.add(
                    column_name
                )

            # ----------------------------------------------
            # Target ports
            # ----------------------------------------------

            if target_instance_name:

                node_ports[
                    target_instance_name
                ] = target_column_names

        # ==================================================
        # TRANSFORMATIONS
        # ==================================================

        transformations = ir.get(
            "transformations",
            []
        )

        if not transformations:

            errors.append(
                "No transformations found in IR"
            )

        transformation_names = set()

        for transformation in transformations:

            name = transformation.get(
                "name"
            )

            transformation_type = (
                transformation.get(
                    "type"
                )
            )

            # ----------------------------------------------
            # Transformation name
            # ----------------------------------------------

            if not name:

                errors.append(
                    "Transformation name is missing"
                )

                continue

            if name in transformation_names:

                errors.append(
                    f"Duplicate transformation "
                    f"found: {name}"
                )

            transformation_names.add(
                name
            )

            # ----------------------------------------------
            # Transformation type
            # ----------------------------------------------

            if not transformation_type:

                errors.append(
                    f"Transformation '{name}' "
                    f"has no type"
                )

                continue

            # ----------------------------------------------
            # Transformation ports
            # ----------------------------------------------

            node_ports[name] = {

                port.get("name")

                for port in transformation.get(
                    "ports",
                    []
                )

                if port.get("name")
            }

            # ----------------------------------------------
            # Transformation config
            # ----------------------------------------------

            config = transformation.get(
                "config",
                {}
            )

            # ==================================================
            # FILTER
            # ==================================================

            if transformation_type == "FILTER":

                if not config.get(
                    "condition"
                ):

                    errors.append(
                        f"FILTER '{name}' "
                        f"is missing condition"
                    )

            # ==================================================
            # LOOKUP
            # ==================================================

            elif transformation_type == "LOOKUP":

                if not config.get(
                    "lookup_source"
                ):

                    errors.append(
                        f"LOOKUP '{name}' "
                        f"is missing lookup_source"
                    )

                if not config.get(
                    "lookup_condition"
                ):

                    errors.append(
                        f"LOOKUP '{name}' "
                        f"is missing lookup_condition"
                    )

            # ==================================================
            # JOINER
            # ==================================================

            elif transformation_type == "JOINER":

                if not config.get(
                    "join_condition"
                ):

                    errors.append(
                        f"JOINER '{name}' "
                        f"is missing join_condition"
                    )

                if not config.get(
                    "join_type"
                ):

                    errors.append(
                        f"JOINER '{name}' "
                        f"is missing join_type"
                    )

            # ==================================================
            # AGGREGATOR
            # ==================================================

            elif transformation_type == "AGGREGATOR":

                if not config.get(
                    "group_by"
                ):

                    errors.append(
                        f"AGGREGATOR '{name}' "
                        f"is missing group_by"
                    )

                aggregate_outputs = [

                    port

                    for port in transformation.get(
                        "ports",
                        []
                    )

                    if port.get(
                        "direction"
                    ) == "OUTPUT"

                    and port.get(
                        "expression"
                    )
                ]

                if not aggregate_outputs:

                    warnings.append(
                        f"AGGREGATOR '{name}' "
                        f"has no aggregate "
                        f"output expressions"
                    )

        # ==================================================
        # VALID GRAPH NODES
        # ==================================================

        valid_nodes = set(
            transformation_names
        )

        # Add actual target instance names.
        #
        # IMPORTANT:
        # We do NOT construct:
        #
        #     TGT_<target_name>
        #
        # because the actual IDMC XML may use
        # any valid target instance name.

        valid_nodes.update(
            target_instance_names
        )

        # ==================================================
        # LINKS
        # ==================================================

        links = ir.get(
            "links",
            []
        )

        if not links:

            errors.append(
                "No links found in IR"
            )

        for link in links:

            from_node = link.get(
                "from"
            )

            from_port = link.get(
                "from_port"
            )

            to_node = link.get(
                "to"
            )

            to_port = link.get(
                "to_port"
            )

            # --------------------------------------------------
            # Normalize link endpoints
            # --------------------------------------------------
            # Depending on the IR shape, a link endpoint may be
            # represented either as:
            #
            #   "from": "SQ_CUSTOMER",
            #   "from_port": "CUSTOMER_ID"
            #
            # or as:
            #
            #   "from": "SQ_CUSTOMER.CUSTOMER_ID"
            #
            # The validator works with node and port separately.
            # Normalize the dotted form here so valid links are
            # not incorrectly reported as unknown nodes.

            if isinstance(from_node, str) and "." in from_node:
                endpoint_node, endpoint_port = from_node.rsplit(".", 1)

                if not from_port:
                    from_port = endpoint_port

                from_node = endpoint_node

            if isinstance(to_node, str) and "." in to_node:
                endpoint_node, endpoint_port = to_node.rsplit(".", 1)

                if not to_port:
                    to_port = endpoint_port

                to_node = endpoint_node

            # ----------------------------------------------
            # Source node
            # ----------------------------------------------

            if not from_node:

                errors.append(
                    "Link is missing source node"
                )

                continue

            # ----------------------------------------------
            # Target node
            # ----------------------------------------------

            if not to_node:

                errors.append(
                    "Link is missing target node"
                )

                continue

            # ----------------------------------------------
            # Source node validation
            # ----------------------------------------------

            if from_node not in valid_nodes:

                errors.append(
                    f"Link references unknown "
                    f"source node: {from_node}"
                )

            # ----------------------------------------------
            # Target node validation
            # ----------------------------------------------

            if to_node not in valid_nodes:

                errors.append(
                    f"Link references unknown "
                    f"target node: {to_node}"
                )

            # ----------------------------------------------
            # Source port validation
            # ----------------------------------------------

            if from_node in node_ports:

                if from_port not in node_ports[
                    from_node
                ]:

                    errors.append(
                        f"Link references unknown "
                        f"source port: "
                        f"{from_node}.{from_port}"
                    )

            # ----------------------------------------------
            # Target port validation
            # ----------------------------------------------

            if to_node in node_ports:

                if to_port not in node_ports[
                    to_node
                ]:

                    errors.append(
                        f"Link references unknown "
                        f"target port: "
                        f"{to_node}.{to_port}"
                    )

        # ==================================================
        # EXECUTION ORDER
        # ==================================================

        execution_order = ir.get(
            "execution_order",
            []
        )

        if not execution_order:

            errors.append(
                "Execution order is missing"
            )

        expected_nodes = set(
            valid_nodes
        )

        actual_nodes = set(
            execution_order
        )

        # ----------------------------------------------
        # Missing nodes
        # ----------------------------------------------

        missing_nodes = (
            expected_nodes
            - actual_nodes
        )

        if missing_nodes:

            errors.append(
                "Execution order missing nodes: "
                + ", ".join(
                    sorted(missing_nodes)
                )
            )

        # ----------------------------------------------
        # Extra nodes
        # ----------------------------------------------

        extra_nodes = (
            actual_nodes
            - expected_nodes
        )

        if extra_nodes:

            errors.append(
                "Execution order contains "
                "unknown nodes: "
                + ", ".join(
                    sorted(extra_nodes)
                )
            )

        # ----------------------------------------------
        # Duplicate nodes
        # ----------------------------------------------

        if len(execution_order) != len(
            actual_nodes
        ):

            errors.append(
                "Execution order contains "
                "duplicate nodes"
            )

        # ==================================================
        # SESSION
        # ==================================================

        session = ir.get(
            "session"
        )

        if not session:

            errors.append(
                "Session information is missing"
            )

        else:

            mapping_name = ir.get(
                "name"
            )

            session_mapping = session.get(
                "mapping"
            )

            if session_mapping != mapping_name:

                errors.append(
                    "Session mapping does not "
                    "match IR mapping"
                )

        # ==================================================
        # FINAL RESULT
        # ==================================================

        status = (
            "VALID"
            if not errors
            else "INVALID"
        )

        return {

            "status": status,

            "errors": errors,

            "warnings": warnings

        }